name: Steven Smith
description: Excited Python developer, creator of cool things
avatar: http://www.gravatar.com/avatar/4043d77a748e3f000d497e1e90502b50?s=140
footer-links:
  github: blha303/blog
  twitter: blha303
  facebook: blha303
  youtube: user/blahblahblahblha303
  email: stevensmith.ome@gmail.com
disqus: blha303blog
url: http://blog.b303.me
baseurl: ""

markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:day/:title/
sass:
  style: :compressed

exclude:
    - LICENSE
    - README.md
    - CNAME

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-archives

jekyll-archives:
  enabled: all
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
  layouts:
    year: archive_year
    month: archive_month
    day: archive_day
    tag: archive_tag
